import { PUBLIC_CODE_ALPHABET, PUBLIC_CODE_LENGTH } from "../constants.ts";
import { containsBlockedPattern } from "./profanity.ts";

// Internal ids use UUIDv7 generated by the application layer (spec §7.1).
// We do not rely on a native Postgres UUIDv7 generator.
export function generateId(): string {
  const bytes = new Uint8Array(16);
  crypto.getRandomValues(bytes);

  const timestamp = Date.now();
  // 48-bit big-endian millisecond timestamp.
  bytes[0] = (timestamp / 0x10000000000) & 0xff;
  bytes[1] = (timestamp / 0x100000000) & 0xff;
  bytes[2] = (timestamp / 0x1000000) & 0xff;
  bytes[3] = (timestamp / 0x10000) & 0xff;
  bytes[4] = (timestamp / 0x100) & 0xff;
  bytes[5] = timestamp & 0xff;

  // Version 7 in the high nibble of byte 6.
  bytes[6] = (bytes[6] & 0x0f) | 0x70;
  // RFC 4122 variant in the high bits of byte 8.
  bytes[8] = (bytes[8] & 0x3f) | 0x80;

  const hex = [...bytes].map((b) => b.toString(16).padStart(2, "0")).join("");
  return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${
    hex.slice(16, 20)
  }-${hex.slice(20)}`;
}

// Generate a single random public code using the safe alphabet (spec §7.2).
// Callers must retry on the rare blocked-pattern hit and on a unique-constraint
// collision when inserting.
export function generatePublicCode(length: number = PUBLIC_CODE_LENGTH): string {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);

  let code = "";
  for (const byte of bytes) {
    code += PUBLIC_CODE_ALPHABET[byte % PUBLIC_CODE_ALPHABET.length];
  }

  // Reject codes that accidentally spell blocked words and try again.
  if (containsBlockedPattern(code)) {
    return generatePublicCode(length);
  }

  return code;
}
